version: "3"
services:
  lang-segment-anything:
    image: nekanat/lang-segment-anything-full:latest
    build: .
    environment:
      - "DISPLAY=${DISPLAY}"
      - "NVIDIA_VISIBLE_DEVICES=all"
      - "NVIDIA_DRIVER_CAPABILITIES=all"
    volumes:
      - ./:/workspace
      - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
    tty: true
    privileged: true
    deploy:
      resources:
        reservations:
          devices:
          - capabilities: [gpu]
